[package]
name = "spookybot"
version = "0.1.0"
authors = ["Tanner Rogalsky <tanner@tannerrogalsky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.9.0-rc.2" }
tokio = { version = "0.2", features = ["macros", "time"] }
rand = "0.7"
