[package]
name = "spookybot"
version = "0.1.0"
authors = ["Tanner Rogalsky <tanner@tannerrogalsky.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11" }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
structopt = "0.3"
dotenv = "0.15"

csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["serde-human-readable"] }