name: Build docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      
      - name: Log in to registry
        run: doctl registry login

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/pluteo/spookybot:latest
          cache-from: type=registry,ref=registry.digitalocean.com/pluteo/spookybot:latest
          cache-to: type=inline